package com.goldex.companion.domain.invoice

import com.goldex.companion.model.BarterInvoice
import com.goldex.companion.model.Customer
import com.goldex.companion.model.CustomerRole
import com.goldex.companion.model.LedgerDirection
import com.goldex.companion.model.LedgerEntryType
import com.goldex.companion.model.LedgerTransaction
import com.goldex.companion.model.SettlementMethod
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import kotlin.math.abs

data class InvoiceSyncResult(
    val transactionsToCreate: List<LedgerTransaction>,
    val updatedCustomer: Customer
)

object InvoiceLedgerSyncUseCase {

    fun generateLedgerSync(
        invoice: BarterInvoice,
        currentCustomer: Customer
    ): InvoiceSyncResult {
        if (!invoice.syncWithLedger) {
            return InvoiceSyncResult(emptyList(), currentCustomer)
        }

        val dateStr = SimpleDateFormat("yyyy/MM/dd HH:mm", Locale.getDefault()).format(Date(invoice.createdAt))
        val transactions = mutableListOf<LedgerTransaction>()
        var customer = currentCustomer

        val balance = invoice.balance

        if (invoice.customerRole == CustomerRole.WHOLESALER) {
            // WHOLESALER: Primary currency is 18k Gold Weight
            // Sales 18k weight vs Received 18k weight
            val net18kWeightDelta = balance.net18kWeightDelta

            // Check if bullion/melt was settled in payments
            val bullionSettledInPayments = invoice.payments
                .filter { it.method == SettlementMethod.BULLION }
                .sumOf { it.goldWeight18k }
            val directBullionSettled = if (invoice.settlementMethod == SettlementMethod.BULLION) {
                invoice.bullionWeight * (invoice.bullionKarat.toDouble() / 750.0)
            } else 0.0
            val totalBullionSettled = bullionSettledInPayments + directBullionSettled

            val cleanInvNum = invoice.cleanInvoiceNumber
            val netWeightToLedger = net18kWeightDelta - totalBullionSettled

            if (abs(netWeightToLedger) >= 0.001) {
                val isPayToCustomer = netWeightToLedger > 0 // Delivered gold to customer -> Customer is debtor
                val direction = if (isPayToCustomer) LedgerDirection.PAY else LedgerDirection.RECEIVE
                val weight = abs(netWeightToLedger)

                val tx = LedgerTransaction(
                    customerId = customer.id,
                    documentNumber = (1000..9999).random().toString(),
                    title = if (isPayToCustomer) "فاکتور تهاتر طلا #$cleanInvNum" else "بستانکاری فاکتور تهاتر #$cleanInvNum",
                    dateTime = dateStr,
                    type = LedgerEntryType.GOLD_WEIGHT,
                    direction = direction,
                    goldCategory = "مصنوعات و آبشده",
                    scaleWeightGrams = weight,
                    karat = 750,
                    equivalent750WeightGrams = weight,
                    note = "ثبت خودکار از فاکتور تهاتر شماره $cleanInvNum",
                    tagBadge = "فاکتور تهاتر",
                    invoiceId = invoice.id,
                    invoiceNumber = cleanInvNum,
                    isAutoGenerated = true,
                    timestamp = invoice.createdAt
                )
                transactions.add(tx)

                val goldDelta = if (direction == LedgerDirection.PAY) weight else -weight
                customer = customer.copy(
                    goldDebtGrams = customer.goldDebtGrams + goldDelta,
                    lastActivityTime = "لحظاتی پیش"
                )
            }

            // Also check if there is an unpaid cash remainder in wholesale deferred to ledger
            if (invoice.settlementMethod == SettlementMethod.LEDGER && invoice.ledgerAmount > 0L) {
                val txCash = LedgerTransaction(
                    customerId = customer.id,
                    documentNumber = (1000..9999).random().toString(),
                    title = "مانده دفتری فاکتور #$cleanInvNum (${invoice.ledgerDueDate})",
                    dateTime = dateStr,
                    type = LedgerEntryType.CASH_RIAL,
                    direction = LedgerDirection.PAY,
                    amountTomans = invoice.ledgerAmount,
                    note = "انتقال مانده ریالی فاکتور به دفتر معین",
                    tagBadge = "دفتر معین",
                    invoiceId = invoice.id,
                    invoiceNumber = cleanInvNum,
                    isAutoGenerated = true,
                    timestamp = invoice.createdAt
                )
                transactions.add(txCash)
                customer = customer.copy(
                    cashDebtTomans = customer.cashDebtTomans + invoice.ledgerAmount,
                    lastActivityTime = "لحظاتی پیش"
                )
            }
        } else {
            // RETAIL: Primary currency is Cash / Toman
            val cleanInvNum = invoice.cleanInvoiceNumber
            val remainingCash = invoice.remainingBalanceTomans
            if (remainingCash > 0L) {
                // Customer owes money
                val tx = LedgerTransaction(
                    customerId = customer.id,
                    documentNumber = (1000..9999).random().toString(),
                    title = "مانده فاکتور فروش طلا #$cleanInvNum",
                    dateTime = dateStr,
                    type = LedgerEntryType.CASH_RIAL,
                    direction = LedgerDirection.PAY,
                    amountTomans = remainingCash,
                    paymentMethod = "مانده دفتری فاکتور",
                    note = "ثبت خودکار مانده پرداخت‌نشده فاکتور $cleanInvNum",
                    tagBadge = "فاکتور فروش",
                    invoiceId = invoice.id,
                    invoiceNumber = cleanInvNum,
                    isAutoGenerated = true,
                    timestamp = invoice.createdAt
                )
                transactions.add(tx)

                customer = customer.copy(
                    cashDebtTomans = customer.cashDebtTomans + remainingCash,
                    lastActivityTime = "لحظاتی پیش"
                )
            } else if (balance.netPayableAmount < -1000.0) {
                // Customer gave more scrap gold than purchase -> creditor
                val creditAmount = abs(balance.netPayableAmount).toLong()
                val tx = LedgerTransaction(
                    customerId = customer.id,
                    documentNumber = (1000..9999).random().toString(),
                    title = "بستانکاری خرید طلا #$cleanInvNum",
                    dateTime = dateStr,
                    type = LedgerEntryType.CASH_RIAL,
                    direction = LedgerDirection.RECEIVE,
                    amountTomans = creditAmount,
                    note = "بستانکاری بابت مازاد طلای متفرقه تحویلی",
                    tagBadge = "خرید طلا",
                    invoiceId = invoice.id,
                    invoiceNumber = cleanInvNum,
                    isAutoGenerated = true,
                    timestamp = invoice.createdAt
                )
                transactions.add(tx)

                customer = customer.copy(
                    cashDebtTomans = customer.cashDebtTomans - creditAmount,
                    lastActivityTime = "لحظاتی پیش"
                )
            }
        }

        return InvoiceSyncResult(transactions, customer)
    }

    fun reverseLedgerSync(
        transactions: List<LedgerTransaction>,
        currentCustomer: Customer
    ): Customer {
        var customer = currentCustomer
        transactions.forEach { tx ->
            when (tx.type) {
                LedgerEntryType.GOLD_WEIGHT -> {
                    val delta = if (tx.direction == LedgerDirection.PAY) {
                        tx.equivalent750WeightGrams
                    } else {
                        -tx.equivalent750WeightGrams
                    }
                    customer = customer.copy(goldDebtGrams = customer.goldDebtGrams - delta)
                }
                LedgerEntryType.CASH_RIAL -> {
                    val delta = if (tx.direction == LedgerDirection.PAY) {
                        tx.amountTomans
                    } else {
                        -tx.amountTomans
                    }
                    customer = customer.copy(cashDebtTomans = customer.cashDebtTomans - delta)
                }
            }
        }
        return customer
    }
}
