package com.goldex.companion.domain.invoice

import com.goldex.companion.data.CustomerStore
import com.goldex.companion.data.InvoiceStore
import com.goldex.companion.data.sync.SyncUnitOfWork
import com.goldex.companion.model.BarterInvoice

class SaveBarterInvoiceUseCase(private val invoices: InvoiceStore, private val customers: CustomerStore?, private val unit: SyncUnitOfWork? = null) {
    fun save(invoice: BarterInvoice) {
        val action = {
            val previous = invoices.getBarterInvoices().firstOrNull { it.id == invoice.id }
            require(previous == null || (previous.debtBasis == invoice.debtBasis &&
                (previous.debtBasis != null || previous.customerRole == invoice.customerRole))) {
                "مبنای بدهی فاکتور ثبت‌شده قابل تغییر نیست"
            }
            require(invoice.debtBasis != com.goldex.companion.model.InvoiceDebtBasis.GOLD ||
                (customers != null && invoice.customer != null && invoice.syncWithLedger && invoice.spotPrice18k > 0)) {
                "برای مانده گرمی، مشتری، اتصال به دفتر و نرخ معتبر لازم است"
            }
            val previousSettlements = customers?.getTransactionsByInvoiceId(invoice.id).orEmpty().filter { it.settlement != null && !it.isAutoGenerated }
            require(previous == null || customers?.getTransactionsByInvoiceId(invoice.id).isNullOrEmpty() ||
                previous.customer?.id == invoice.customer?.id) {
                "طرف حساب فاکتور ثبت‌شده قابل تغییر نیست؛ ابتدا اسناد آن را برگشت دهید"
            }
            require(previousSettlements.isEmpty() || (invoice.syncWithLedger && previousSettlements.all { it.customerId == invoice.customer?.id })) {
                "فاکتور دارای تسویه است؛ اتصال آن به مشتری و دفتر باید حفظ شود"
            }
            if (previous != null && invoice.debtBasis != null && previousSettlements.isNotEmpty()) {
                require(invoice.spotPrice18k == previous.spotPrice18k && invoice.salesItems == previous.salesItems &&
                    invoice.receivedItems == previous.receivedItems) {
                    "فاکتور دارای تسویه است؛ برای اصلاح مبلغ یا نرخ ابتدا تسویه‌ها را برگشت دهید"
                }
            }
            val datedIds = previousSettlements.map { it.id }.toSet()
            require(invoice.payments.none { it.settlement != null && it.id !in datedIds }) {
                "سند تسویه فاکتور در دفتر موجود نیست؛ ابتدا همگام‌سازی حساب را تکمیل کنید"
            }
            val savedInvoice = invoice.copy(payments = invoice.payments.filterNot { it.id in datedIds || it.settlement != null } +
                previous?.payments.orEmpty().filter { it.id in datedIds })
            invoices.saveBarterInvoice(savedInvoice)
            val target = invoice.customer
            if (target != null && customers != null) {
                val original = customers.getCustomers().firstOrNull { it.id == target.id }
                    ?: error("Invoice customer is missing")
                val allEntries = customers.getTransactionsByInvoiceId(invoice.id)
                val settlements = allEntries.filter { it.settlement != null && !it.isAutoGenerated }
                require(settlements.isEmpty() || (invoice.syncWithLedger && settlements.all { it.customerId == target.id })) {
                    "فاکتور دارای تسویه است؛ اتصال آن به مشتری و دفتر باید حفظ شود"
                }
                val entries = allEntries.filterNot { it in settlements }
                val reversed = if (entries.isNotEmpty()) InvoiceLedgerSyncUseCase.reverseLedgerSync(entries, original) else original
                if (allEntries.isNotEmpty()) customers.deleteTransactionsByInvoiceId(invoice.id)
                settlements.forEach(customers::addTransaction)
                if (invoice.syncWithLedger) {
                    val settlementIds = settlements.map { it.id }.toSet()
                    val unsyncedPayments = savedInvoice.payments.filterNot { it.id in settlementIds }
                    val invoiceForSync = if (savedInvoice.payments.isNotEmpty()) savedInvoice.copy(
                        payments = unsyncedPayments, cashPosAmount = 0L, ledgerAmount = 0L,
                        bullionWeight = 0.0, thirdPartyTransferAmount = 0L, thirdPartyTransferWeight18k = 0.0
                    ) else savedInvoice
                    val result = InvoiceLedgerSyncUseCase.generateLedgerSync(invoiceForSync, reversed)
                    result.transactionsToCreate.forEach(customers::addTransaction)
                    customers.updateCustomer(result.updatedCustomer)
                } else if (entries.isNotEmpty()) customers.updateCustomer(reversed)
            }
        }
        if (unit == null) action() else unit.transaction(action)
    }
}
