package com.goldex.companion.data.sync

import com.goldex.companion.data.*
import com.goldex.companion.model.*
import org.json.*
import java.math.BigDecimal

/** Keep existing compatibility codecs; all wire numbers are strings, including nested snapshots. */
object SyncJson {
    fun numericStrings(value: Any?): Any? = when (value) {
        is JSONObject -> JSONObject().also { result -> value.keys().forEach { result.put(it, numericStrings(value.get(it))) } }
        is JSONArray -> JSONArray().also { result -> (0 until value.length()).forEach { result.put(numericStrings(value.get(it))) } }
        is BigDecimal -> value.toPlainString()
        is Double -> { require(value.isFinite()); BigDecimal.valueOf(value).toPlainString() }
        is Float -> { require(value.isFinite()); BigDecimal(value.toString()).toPlainString() }
        is Number -> value.toString()
        is String -> {
            if (value.isNotEmpty() && (value.contains('e') || value.contains('E')) && (value.first().isDigit() || value.first() == '-')) {
                runCatching { BigDecimal(value).toPlainString() }.getOrDefault(value)
            } else value
        }
        else -> value
    }
    fun record(value: Any): JSONObject {
        val json = when (value) {
            is Customer -> PersistenceJsonCodecs.encodeCustomers(listOf(value))
            is LedgerTransaction -> PersistenceJsonCodecs.encodeLedgerTransactions(listOf(value))
            is BarterInvoice -> PersistenceJsonCodecs.encodeBarterInvoices(listOf(value))
            is Invoice -> PersistenceJsonCodecs.encodeInvoices(listOf(value))
            is InventoryItem -> PersistenceJsonCodecs.encodeInventoryItems(listOf(value))
            is StockAdjustment -> PersistenceJsonCodecs.encodeStockAdjustments(listOf(value))
            is PortfolioItem -> PersistenceJsonCodecs.encodePortfolioItems(listOf(value))
            else -> error("Unsupported record")
        }
        return numericStrings(JSONArray(json).getJSONObject(0)) as JSONObject
    }
    fun business(s: AppSettings): JSONObject = JSONObject().put("id", "business")
        .put("galleryName", s.galleryName).put("managerName", s.managerName).put("unionCode", s.unionCode)
        .put("galleryPhone", s.galleryPhone).put("galleryAddress", s.galleryAddress).put("galleryLicense", s.galleryLicense)
        .put("defaultProfitPercent", s.defaultProfitPercent).put("defaultTaxPercent", s.defaultTaxPercent)
        .put("defaultWageType", s.defaultWageType.name).put("priceSource", s.priceSource.name).put("autoSyncRates", s.autoSyncRates)
    fun applyBusiness(s: AppSettings, j: JSONObject): AppSettings = s.copy(
        galleryName=j.getString("galleryName"), managerName=j.getString("managerName"), unionCode=j.getString("unionCode"),
        galleryPhone=j.getString("galleryPhone"), galleryAddress=j.getString("galleryAddress"), galleryLicense=j.getString("galleryLicense"),
        defaultProfitPercent=j.getString("defaultProfitPercent"), defaultTaxPercent=j.getString("defaultTaxPercent"),
        defaultWageType=WageType.valueOf(j.getString("defaultWageType")), priceSource=PriceSource.valueOf(j.getString("priceSource")), autoSyncRates=j.getBoolean("autoSyncRates"))
    fun canonical(value: Any?): String = when(value) {
        is JSONObject -> value.keys().asSequence().toList().sorted().joinToString(",", "{", "}") { JSONObject.quote(it) + ":" + canonical(value.get(it)) }
        is JSONArray -> (0 until value.length()).joinToString(",", "[", "]") { canonical(value.get(it)) }
        is String -> JSONObject.quote(value)
        null, JSONObject.NULL -> "null"
        else -> value.toString()
    }
    private val knownFields = mapOf(
        "customer" to setOf("accountCode","cashDebtTomans","cityOrMarket","createdAt","goldDebtGrams","id","isVerified","lastActivityTime","name","nationalId","note","phone","role"),
        "ledger" to setOf("settlement","amountTomans","angNumber","customerId","dateTime","destinationBank","direction","documentNumber","equivalent750WeightGrams","goldCategory","id","invoiceId","invoiceNumber","isAutoGenerated","karat","labName","note","paymentMethod","resultingCashBalance","resultingGoldBalance","scaleWeightGrams","tagBadge","timestamp","title","trackingCode","type"),
        "invoice" to setOf("createdAt","customKaratValue","customer","effectiveGramPrice","grossWeight","id","invoiceNumber","items","karat","netWeight","note","profitAmount","profitPercent","rawGoldValue","spotPrice","stoneWeight","taxAmount","taxPercent","title","totalPayable","wageAmount","wageInput","wageType"),
        "barterInvoice" to setOf("debtBasis","amountTomans","angNumber","baseKarat","bullionAngNumber","bullionKarat","bullionWeight","cashPosAmount","category","coinType","count","createdAt","customKaratValue","customer","customerRole","date","deductionPerGram","description","effectiveGramPrice","equivalent18kWeight","exchangeCommissionPercent","goldWeight18k","grossWeight","hasHologram","id","invoiceNumber","karat","karatDeficit","labKarat","labName","ledgerAmount","ledgerDueDate","method","netWeight","note","payableKarat","payments","posTrackingCode","profitAmount","profitPercent","rawGoldValue","receivedItems","salesItems","settlementMethod","spotPrice","spotPrice18k","stoneWeight","syncWithLedger","taxAmount","taxPercent","thirdPartyCustomer","thirdPartyCustomerName","thirdPartyInvoiceId","thirdPartyInvoiceNumber","thirdPartyTrackingCode","thirdPartyTransferAmount","thirdPartyTransferWeight18k","title","totalPayable","trackingCode","unitPrice","wageAmount","wageInput","wageType","weight"),
        "inventory" to setOf("category","code","createdAt","customKaratValue","grossWeightGrams","id","imageUrl","karat","location","profitPercent","quantity","rfidTag","stoneWeightGrams","taxPercent","title","wagePercent","wageType","wageValue","workshop"),
        "stockAdjustment" to setOf("coinBahar","coinEmami","coinGerami","coinHalf","coinQuarter","gold18","gold24","goldMelt","id","isLive","itemId","itemTitle","lastUpdated","note","ons","quantityChange","reason","source","timestamp","type","usd","weightGrams"),
        "portfolio" to setOf("category","coinType","id","karat","purchaseDate","purchasePriceTotal","quantity","title","weightGrams"),
        "businessSettings" to setOf("id","galleryName","managerName","unionCode","galleryPhone","galleryAddress","galleryLicense","defaultProfitPercent","defaultTaxPercent","defaultWageType","priceSource","autoSyncRates","logoAssetId","stampAssetId","signatureAssetId")
    )
    fun preserveUnknown(type: String, old: JSONObject?, fresh: JSONObject?): JSONObject? {
        if(fresh==null || old==null) return fresh
        val result=JSONObject(fresh.toString())
        old.keys().forEach { if(it !in knownFields.getValue(type) && !result.has(it)) result.put(it,old.get(it)) }
        return result
    }
    fun diff(old: JSONObject?, fresh: JSONObject?): JSONObject {
        if (fresh == null) return JSONObject().put("action", "delete")
        if (old == null) return JSONObject().put("action", "create").put("fields", fresh)
        val fields = JSONObject(); val remove = JSONArray()
        fresh.keys().forEach { key -> if (!old.has(key) || canonical(old.get(key)) != canonical(fresh.get(key))) fields.put(key, fresh.get(key)) }
        old.keys().forEach { key -> if (!fresh.has(key)) remove.put(key) }
        return JSONObject().put("action", "patch").put("fields", fields).put("remove", remove)
    }
    fun apply(old: JSONObject?, change: JSONObject): JSONObject? {
        if (change.getString("action") == "delete") return null
        val result = if (change.getString("action") == "create") JSONObject() else JSONObject(requireNotNull(old).toString())
        change.optJSONObject("fields")?.let { fields -> fields.keys().forEach { result.put(it, fields.get(it)) } }
        change.optJSONArray("remove")?.let { remove -> (0 until remove.length()).forEach { result.remove(remove.getString(it)) } }
        return result
    }
}
