package com.goldex.companion

import com.goldex.companion.data.PersistenceJsonCodecs
import com.goldex.companion.domain.invoice.BarterCalculationUseCases
import com.goldex.companion.domain.invoice.InvoiceLedgerSyncUseCase
import com.goldex.companion.model.*
import org.junit.Assert.*
import org.junit.Test

class InvoiceLedgerSyncTest {

    @Test
    fun testWholesalerInvoiceSyncGeneratesGoldWeightTransaction() {
        val initialCustomer = Customer(
            id = "c-wholesaler-1",
            name = "حاج قاسم زرگر",
            goldDebtGrams = 0.0,
            cashDebtTomans = 0L,
            role = "بنکدار و کیفی"
        )

        val craftedItem = BarterCalculationUseCases.calculateCraftedItem(
            title = "دستبند کارتیه",
            karat = Karat.K18,
            grossWeight = 25.0,
            stoneWeight = 0.0,
            spotPrice18k = 24_000_000L,
            wageType = WageType.PERCENTAGE,
            wageInput = 10.0,
            profitPercent = 7.0,
            taxPercent = 9.0
        )

        val scrapItem = BarterCalculationUseCases.calculateScrapItem(
            title = "طلای متفرقه",
            baseKarat = 750,
            karatDeficit = 0,
            grossWeight = 5.0,
            stoneWeight = 0.0,
            spotPrice18k = 24_000_000L
        )

        val invoice = BarterInvoice(
            id = "inv-101",
            invoiceNumber = "1403-101",
            customer = initialCustomer,
            customerRole = CustomerRole.WHOLESALER,
            salesItems = listOf(craftedItem), // 25.0g 18k
            receivedItems = listOf(scrapItem), // 5.0g 18k
            syncWithLedger = true
        )

        val result = InvoiceLedgerSyncUseCase.generateLedgerSync(invoice, initialCustomer)

        assertEquals(1, result.transactionsToCreate.size)
        val tx = result.transactionsToCreate.single()

        assertEquals("inv-101", tx.invoiceId)
        assertEquals("1403-101", tx.invoiceNumber)
        assertTrue(tx.documentNumber.isNotBlank())
        assertFalse(tx.documentNumber.startsWith("IR"))
        assertTrue(tx.isAutoGenerated)
        assertEquals(LedgerEntryType.GOLD_WEIGHT, tx.type)
        assertEquals(LedgerDirection.PAY, tx.direction)
        assertEquals(20.0, tx.equivalent750WeightGrams, 0.001)

        assertEquals(20.0, result.updatedCustomer.goldDebtGrams, 0.001)
        assertEquals(0L, result.updatedCustomer.cashDebtTomans)
    }

    @Test
    fun testWholesalerWithBullionSettlementDeduction() {
        val customer = Customer(
            id = "c-wholesaler-2",
            name = "همکار بازاری",
            goldDebtGrams = 10.0,
            cashDebtTomans = 0L
        )

        val craftedItem = BarterCalculationUseCases.calculateCraftedItem(
            title = "انگشتر طلا",
            karat = Karat.K18,
            grossWeight = 30.0,
            stoneWeight = 0.0,
            spotPrice18k = 24_000_000L,
            wageType = WageType.PERCENTAGE,
            wageInput = 10.0,
            profitPercent = 7.0,
            taxPercent = 9.0
        )

        val invoice = BarterInvoice(
            id = "inv-102",
            invoiceNumber = "1403-102",
            customer = customer,
            customerRole = CustomerRole.WHOLESALER,
            salesItems = listOf(craftedItem), // 30.0g
            payments = listOf(
                SettlementPaymentItem(
                    method = SettlementMethod.BULLION,
                    goldWeight18k = 18.0,
                    description = "تحویل شمش آبشده"
                )
            ),
            syncWithLedger = true
        )

        val result = InvoiceLedgerSyncUseCase.generateLedgerSync(invoice, customer)

        assertEquals(1, result.transactionsToCreate.size)
        val tx = result.transactionsToCreate.single()
        assertEquals(12.0, tx.equivalent750WeightGrams, 0.001) // 30 - 18 = 12g
        assertEquals(22.0, result.updatedCustomer.goldDebtGrams, 0.001) // 10 initial + 12
    }

    @Test
    fun testRetailInvoiceSyncGeneratesCashDebtTransaction() {
        val retailCustomer = Customer(
            id = "c-retail-1",
            name = "مشتری عادی",
            goldDebtGrams = 0.0,
            cashDebtTomans = 0L,
            role = "مشتری عادی"
        )

        val craftedItem = BarterCalculationUseCases.calculateCraftedItem(
            title = "گردنبند طلا",
            karat = Karat.K18,
            grossWeight = 5.0,
            stoneWeight = 0.0,
            spotPrice18k = 20_000_000L,
            wageType = WageType.PERCENTAGE,
            wageInput = 0.0,
            profitPercent = 0.0,
            taxPercent = 0.0
        ) // 5 * 20M = 100,000,000 Tomans

        val invoice = BarterInvoice(
            id = "inv-retail-1",
            invoiceNumber = "1403-201",
            customer = retailCustomer,
            customerRole = CustomerRole.RETAIL,
            salesItems = listOf(craftedItem),
            payments = listOf(
                SettlementPaymentItem(
                    method = SettlementMethod.POS,
                    amountTomans = 70_000_000L,
                    trackingCode = "998877"
                )
            ),
            syncWithLedger = true
        )

        val result = InvoiceLedgerSyncUseCase.generateLedgerSync(invoice, retailCustomer)

        assertEquals(1, result.transactionsToCreate.size)
        val tx = result.transactionsToCreate.single()
        assertEquals(LedgerEntryType.CASH_RIAL, tx.type)
        assertEquals(LedgerDirection.PAY, tx.direction)
        assertEquals(30_000_000L, tx.amountTomans)
        assertEquals("inv-retail-1", tx.invoiceId)
        assertTrue(tx.isAutoGenerated)

        assertEquals(0.0, result.updatedCustomer.goldDebtGrams, 0.0001)
        assertEquals(30_000_000L, result.updatedCustomer.cashDebtTomans)
    }

    @Test
    fun testSyncWithLedgerDisabledProducesNoTransactions() {
        val customer = Customer(id = "c1", name = "تست", goldDebtGrams = 5.0, cashDebtTomans = 100L)
        val invoice = BarterInvoice(
            id = "inv-off",
            customer = customer,
            syncWithLedger = false
        )

        val result = InvoiceLedgerSyncUseCase.generateLedgerSync(invoice, customer)
        assertTrue(result.transactionsToCreate.isEmpty())
        assertEquals(5.0, result.updatedCustomer.goldDebtGrams, 0.001)
        assertEquals(100L, result.updatedCustomer.cashDebtTomans)
    }

    @Test
    fun testReverseLedgerSyncRestoresCustomerBalance() {
        val original = Customer(id = "c1", name = "تست", goldDebtGrams = 10.0, cashDebtTomans = 50_000_000L)

        val goldTx = LedgerTransaction(
            type = LedgerEntryType.GOLD_WEIGHT,
            direction = LedgerDirection.PAY,
            equivalent750WeightGrams = 8.0,
            customerId = "c1"
        )
        val cashTx = LedgerTransaction(
            type = LedgerEntryType.CASH_RIAL,
            direction = LedgerDirection.PAY,
            amountTomans = 20_000_000L,
            customerId = "c1"
        )

        val modified = original.copy(
            goldDebtGrams = original.goldDebtGrams + 8.0,
            cashDebtTomans = original.cashDebtTomans + 20_000_000L
        )
        assertEquals(18.0, modified.goldDebtGrams, 0.001)
        assertEquals(70_000_000L, modified.cashDebtTomans)

        val restored = InvoiceLedgerSyncUseCase.reverseLedgerSync(listOf(goldTx, cashTx), modified)
        assertEquals(10.0, restored.goldDebtGrams, 0.001)
        assertEquals(50_000_000L, restored.cashDebtTomans)
    }

    @Test
    fun testLedgerTransactionWithInvoiceLinkRoundTrip() {
        val tx = LedgerTransaction(
            id = "tx-auto-1",
            customerId = "c-100",
            documentNumber = "IR-1403-999",
            title = "فاکتور تهاتر طلا",
            dateTime = "۱۴۰۳/۰۶/۲۵ ۱۰:۰۰",
            type = LedgerEntryType.GOLD_WEIGHT,
            direction = LedgerDirection.PAY,
            equivalent750WeightGrams = 14.500,
            invoiceId = "inv-target-1",
            invoiceNumber = "IR-1403-999",
            isAutoGenerated = true
        )

        val json = PersistenceJsonCodecs.encodeLedgerTransactions(listOf(tx))
        val decoded = PersistenceJsonCodecs.decodeLedgerTransactions(json).single()

        assertEquals("tx-auto-1", decoded.id)
        assertEquals("c-100", decoded.customerId)
        assertEquals("inv-target-1", decoded.invoiceId)
        assertEquals("IR-1403-999", decoded.invoiceNumber)
        assertTrue(decoded.isAutoGenerated)
        assertEquals(14.500, decoded.equivalent750WeightGrams, 0.001)
    }

    @Test
    fun testBarterInvoiceSerializationRoundTrip() {
        val invoice = BarterInvoice(
            id = "inv-full-1",
            invoiceNumber = "IR-1404-555",
            createdAt = 1715000000000L,
            customer = Customer(id = "c55", name = "جواد زرگر", phone = "09123334455"),
            customerRole = CustomerRole.WHOLESALER,
            spotPrice18k = 24_500_000L,
            salesItems = listOf(
                CraftedGoldItem(
                    id = "item-1",
                    title = "سرویس طلا",
                    karat = Karat.K18,
                    customKaratValue = 750,
                    grossWeight = 12.0,
                    stoneWeight = 0.0,
                    netWeight = 12.0,
                    spotPrice = 24_500_000L,
                    wageType = WageType.PERCENTAGE,
                    wageInput = 8.0,
                    wageAmount = 23_520_000.0,
                    profitPercent = 7.0,
                    profitAmount = 22_241_440.0,
                    taxPercent = 9.0,
                    taxAmount = 4_118_529.6,
                    rawGoldValue = 294_000_000.0,
                    totalPayable = 343_879_969.6,
                    equivalent18kWeight = 12.0
                )
            ),
            payments = listOf(
                SettlementPaymentItem(
                    id = "pay-1",
                    method = SettlementMethod.POS,
                    amountTomans = 200_000_000L,
                    trackingCode = "POS-7788"
                )
            ),
            syncWithLedger = true,
            note = "تحویل فوری در سرای امید"
        )

        val json = PersistenceJsonCodecs.encodeBarterInvoices(listOf(invoice))
        val decodedList = PersistenceJsonCodecs.decodeBarterInvoices(json)

        assertEquals(1, decodedList.size)
        val decoded = decodedList.single()

        assertEquals("inv-full-1", decoded.id)
        assertEquals("IR-1404-555", decoded.invoiceNumber)
        assertEquals("جواد زرگر", decoded.customer?.name)
        assertEquals(CustomerRole.WHOLESALER, decoded.customerRole)
        assertEquals(24_500_000L, decoded.spotPrice18k)
        assertEquals(1, decoded.salesItems.size)
        assertEquals("سرویس طلا", decoded.salesItems.first().title)
        assertEquals(1, decoded.payments.size)
        assertEquals(200_000_000L, decoded.payments.first().amountTomans)
        assertTrue(decoded.syncWithLedger)
        assertEquals("تحویل فوری در سرای امید", decoded.note)
        assertEquals("1404-555", decoded.cleanInvoiceNumber)
    }

    @Test
    fun testCleanInvoiceNumberAndCleanDocumentNumberRemovesIRPrefix() {
        val legacyInvoice = BarterInvoice(
            invoiceNumber = "IR-1403-888"
        )
        assertEquals("1403-888", legacyInvoice.cleanInvoiceNumber)

        val legacyTx = LedgerTransaction(
            customerId = "c1",
            documentNumber = "IR-8842",
            invoiceNumber = "IR-1403-777"
        )
        assertEquals("8842", legacyTx.cleanDocumentNumber)
        assertEquals("1403-777", legacyTx.cleanInvoiceNumber)

        val modernInvoice = BarterInvoice(
            invoiceNumber = "1403-999"
        )
        assertEquals("1403-999", modernInvoice.cleanInvoiceNumber)
    }
}
