package com.goldex.companion

import com.goldex.companion.data.PersistenceJsonCodecs
import com.goldex.companion.domain.invoice.BarterCalculationUseCases
import com.goldex.companion.domain.invoice.InvoiceLedgerSyncUseCase
import com.goldex.companion.model.*
import org.junit.Assert.*
import org.junit.Test

class InvoiceLedgerSyncTest {

    @Test
    fun testWholesalerInvoiceSyncGeneratesGoldWeightTransaction() {
        val initialCustomer = Customer(
            id = "c-wholesaler-1",
            name = "حاج قاسم زرگر",
            goldDebtGrams = 0.0,
            cashDebtTomans = 0L,
            role = "بنکدار و کیفی"
        )

        val craftedItem = BarterCalculationUseCases.calculateCraftedItem(
            title = "دستبند کارتیه",
            karat = Karat.K18,
            grossWeight = 25.0,
            stoneWeight = 0.0,
            spotPrice18k = 24_000_000L,
            wageType = WageType.PERCENTAGE,
            wageInput = 10.0,
            profitPercent = 7.0,
            taxPercent = 9.0
        )

        val scrapItem = BarterCalculationUseCases.calculateScrapItem(
            title = "طلای متفرقه",
            baseKarat = 750,
            karatDeficit = 0,
            grossWeight = 5.0,
            stoneWeight = 0.0,
            spotPrice18k = 24_000_000L
        )

        val invoice = BarterInvoice(
            id = "inv-101",
            invoiceNumber = "1403-101",
            customer = initialCustomer,
            customerRole = CustomerRole.WHOLESALER,
            salesItems = listOf(craftedItem), // 25.0g 18k
            receivedItems = listOf(scrapItem), // 5.0g 18k
            syncWithLedger = true
        )

        val result = InvoiceLedgerSyncUseCase.generateLedgerSync(invoice, initialCustomer)

        assertEquals(1, result.transactionsToCreate.size)
        val tx = result.transactionsToCreate.single()

        assertEquals("inv-101", tx.invoiceId)
        assertEquals("1403-101", tx.invoiceNumber)
        assertTrue(tx.documentNumber.isNotBlank())
        assertFalse(tx.documentNumber.startsWith("IR"))
        assertTrue(tx.isAutoGenerated)
        assertEquals(LedgerEntryType.GOLD_WEIGHT, tx.type)
        assertEquals(LedgerDirection.PAY, tx.direction)
        assertEquals(20.0, tx.equivalent750WeightGrams, 0.001)

        assertEquals(20.0, result.updatedCustomer.goldDebtGrams, 0.001)
        assertEquals(0L, result.updatedCustomer.cashDebtTomans)
    }

    @Test
    fun testWholesalerWithBullionSettlementDeduction() {
        val customer = Customer(
            id = "c-wholesaler-2",
            name = "همکار بازاری",
            goldDebtGrams = 10.0,
            cashDebtTomans = 0L
        )

        val craftedItem = BarterCalculationUseCases.calculateCraftedItem(
            title = "انگشتر طلا",
            karat = Karat.K18,
            grossWeight = 30.0,
            stoneWeight = 0.0,
            spotPrice18k = 24_000_000L,
            wageType = WageType.PERCENTAGE,
            wageInput = 10.0,
            profitPercent = 7.0,
            taxPercent = 9.0
        )

        val invoice = BarterInvoice(
            id = "inv-102",
            invoiceNumber = "1403-102",
            customer = customer,
            customerRole = CustomerRole.WHOLESALER,
            salesItems = listOf(craftedItem), // 30.0g
            payments = listOf(
                SettlementPaymentItem(
                    method = SettlementMethod.BULLION,
                    goldWeight18k = 18.0,
                    description = "تحویل شمش آبشده",
                    bullionAngNumber = "9912"
                )
            ),
            syncWithLedger = true
        )

        val result = InvoiceLedgerSyncUseCase.generateLedgerSync(invoice, customer)

        // Both the 30g invoice obligation and the 18g bullion receipt are recorded
        assertEquals(2, result.transactionsToCreate.size)
        val invoiceTx = result.transactionsToCreate[0]
        assertEquals(LedgerEntryType.GOLD_WEIGHT, invoiceTx.type)
        assertEquals(LedgerDirection.PAY, invoiceTx.direction)
        assertEquals(30.0, invoiceTx.equivalent750WeightGrams, 0.001)

        val bullionTx = result.transactionsToCreate[1]
        assertEquals(LedgerEntryType.GOLD_WEIGHT, bullionTx.type)
        assertEquals(LedgerDirection.RECEIVE, bullionTx.direction)
        assertEquals(18.0, bullionTx.equivalent750WeightGrams, 0.001)
        assertEquals("9912", bullionTx.angNumber)

        // Net gold debt: 10.0 (initial) + 30.0 (invoice) - 18.0 (bullion) = 22.0g
        assertEquals(22.0, result.updatedCustomer.goldDebtGrams, 0.001)
    }

    @Test
    fun testRetailInvoiceSyncGeneratesCashDebtAndPaymentTransactions() {
        val retailCustomer = Customer(
            id = "c-retail-1",
            name = "مشتری عادی",
            goldDebtGrams = 0.0,
            cashDebtTomans = 0L,
            role = "مشتری عادی"
        )

        val craftedItem = BarterCalculationUseCases.calculateCraftedItem(
            title = "گردنبند طلا",
            karat = Karat.K18,
            grossWeight = 5.0,
            stoneWeight = 0.0,
            spotPrice18k = 20_000_000L,
            wageType = WageType.PERCENTAGE,
            wageInput = 0.0,
            profitPercent = 0.0,
            taxPercent = 0.0
        ) // 5 * 20M = 100,000,000 Tomans

        val invoice = BarterInvoice(
            id = "inv-retail-1",
            invoiceNumber = "1403-201",
            customer = retailCustomer,
            customerRole = CustomerRole.RETAIL,
            salesItems = listOf(craftedItem),
            payments = listOf(
                SettlementPaymentItem(
                    method = SettlementMethod.POS,
                    amountTomans = 70_000_000L,
                    trackingCode = "998877"
                )
            ),
            syncWithLedger = true
        )

        val result = InvoiceLedgerSyncUseCase.generateLedgerSync(invoice, retailCustomer)

        // 1 Invoice charge transaction (100M) + 1 POS payment transaction (70M)
        assertEquals(2, result.transactionsToCreate.size)
        val invoiceTx = result.transactionsToCreate[0]
        assertEquals(LedgerEntryType.CASH_RIAL, invoiceTx.type)
        assertEquals(LedgerDirection.PAY, invoiceTx.direction)
        assertEquals(100_000_000L, invoiceTx.amountTomans)
        assertEquals("inv-retail-1", invoiceTx.invoiceId)
        assertTrue(invoiceTx.isAutoGenerated)

        val paymentTx = result.transactionsToCreate[1]
        assertEquals(LedgerEntryType.CASH_RIAL, paymentTx.type)
        assertEquals(LedgerDirection.RECEIVE, paymentTx.direction)
        assertEquals(70_000_000L, paymentTx.amountTomans)
        assertEquals("998877", paymentTx.trackingCode)
        assertEquals("تسویه کارتخوان", paymentTx.tagBadge)
        assertEquals("inv-retail-1", paymentTx.invoiceId)

        // Net debt: 100M - 70M = 30M Tomans
        assertEquals(0.0, result.updatedCustomer.goldDebtGrams, 0.0001)
        assertEquals(30_000_000L, result.updatedCustomer.cashDebtTomans)
    }

    @Test
    fun testRetailInvoiceWithFullPaymentRecordsBothTransactionsAndZeroBalance() {
        val retailCustomer = Customer(
            id = "c-retail-full",
            name = "مشتری تسویه نقدی",
            goldDebtGrams = 0.0,
            cashDebtTomans = 0L
        )

        val craftedItem = BarterCalculationUseCases.calculateCraftedItem(
            title = "گوشواره",
            karat = Karat.K18,
            grossWeight = 2.0,
            stoneWeight = 0.0,
            spotPrice18k = 25_000_000L,
            wageType = WageType.PERCENTAGE,
            wageInput = 0.0,
            profitPercent = 0.0,
            taxPercent = 0.0
        ) // 2 * 25M = 50,000,000 Tomans

        val invoice = BarterInvoice(
            id = "inv-full",
            invoiceNumber = "1403-202",
            customer = retailCustomer,
            customerRole = CustomerRole.RETAIL,
            salesItems = listOf(craftedItem),
            payments = listOf(
                SettlementPaymentItem(
                    method = SettlementMethod.POS,
                    amountTomans = 50_000_000L,
                    trackingCode = "123456"
                )
            ),
            syncWithLedger = true
        )

        val result = InvoiceLedgerSyncUseCase.generateLedgerSync(invoice, retailCustomer)

        assertEquals(2, result.transactionsToCreate.size)
        val invoiceTx = result.transactionsToCreate[0]
        val posTx = result.transactionsToCreate[1]

        assertEquals(LedgerDirection.PAY, invoiceTx.direction)
        assertEquals(50_000_000L, invoiceTx.amountTomans)

        assertEquals(LedgerDirection.RECEIVE, posTx.direction)
        assertEquals(50_000_000L, posTx.amountTomans)

        // Customer debt is fully settled (0 Tomans)
        assertEquals(0L, result.updatedCustomer.cashDebtTomans)
    }

    @Test
    fun testRetailScrapGoldPurchaseWithShopPaymentToCustomer() {
        val customer = Customer(
            id = "c-seller",
            name = "فروشنده طلای کهنه",
            goldDebtGrams = 0.0,
            cashDebtTomans = 0L
        )

        // Customer sells 2.0g scrap gold at 20,000,000 spot = 40,000,000 Tomans
        val scrapItem = BarterCalculationUseCases.calculateScrapItem(
            title = "طلای کهنه",
            baseKarat = 750,
            karatDeficit = 0,
            grossWeight = 2.0,
            stoneWeight = 0.0,
            spotPrice18k = 20_000_000L,
            deductionPerGram = 0L
        )

        val invoice = BarterInvoice(
            id = "inv-scrap-1",
            invoiceNumber = "1403-301",
            customer = customer,
            customerRole = CustomerRole.RETAIL,
            receivedItems = listOf(scrapItem),
            payments = listOf(
                SettlementPaymentItem(
                    method = SettlementMethod.POS,
                    amountTomans = 40_000_000L,
                    trackingCode = "PAY-9988"
                )
            ),
            syncWithLedger = true
        )

        val result = InvoiceLedgerSyncUseCase.generateLedgerSync(invoice, customer)

        assertEquals(2, result.transactionsToCreate.size)
        // 1. Scrap purchase credit transaction (shop received gold -> customer is credited)
        val purchaseTx = result.transactionsToCreate[0]
        assertEquals(LedgerEntryType.CASH_RIAL, purchaseTx.type)
        assertEquals(LedgerDirection.RECEIVE, purchaseTx.direction)
        assertEquals(40_000_000L, purchaseTx.amountTomans)
        assertEquals("خرید طلا", purchaseTx.tagBadge)

        // 2. Shop payment to customer transaction (shop pays money to customer)
        val paymentTx = result.transactionsToCreate[1]
        assertEquals(LedgerEntryType.CASH_RIAL, paymentTx.type)
        assertEquals(LedgerDirection.PAY, paymentTx.direction)
        assertEquals(40_000_000L, paymentTx.amountTomans)
        assertEquals("تسویه خرید طلا", paymentTx.tagBadge)

        // Balances out to 0
        assertEquals(0L, result.updatedCustomer.cashDebtTomans)
    }

    @Test
    fun testRetailScrapGoldPurchaseWithPartialPayment() {
        val customer = Customer(
            id = "c-seller-partial",
            name = "فروشنده طلای کهنه",
            goldDebtGrams = 0.0,
            cashDebtTomans = 0L
        )

        val scrapItem = BarterCalculationUseCases.calculateScrapItem(
            title = "طلای کهنه",
            baseKarat = 750,
            karatDeficit = 0,
            grossWeight = 2.5,
            stoneWeight = 0.0,
            spotPrice18k = 20_000_000L,
            deductionPerGram = 0L
        ) // 50,000,000 Tomans

        val invoice = BarterInvoice(
            id = "inv-scrap-2",
            invoiceNumber = "1403-302",
            customer = customer,
            customerRole = CustomerRole.RETAIL,
            receivedItems = listOf(scrapItem),
            payments = listOf(
                SettlementPaymentItem(
                    method = SettlementMethod.TRANSFER,
                    amountTomans = 30_000_000L,
                    trackingCode = "TR-5544"
                )
            ),
            syncWithLedger = true
        )

        val result = InvoiceLedgerSyncUseCase.generateLedgerSync(invoice, customer)

        assertEquals(2, result.transactionsToCreate.size)
        // Customer was credited 50M, shop paid 30M -> customer remains creditor for 20M (-20,000,000)
        assertEquals(-20_000_000L, result.updatedCustomer.cashDebtTomans)
    }

    @Test
    fun testWholesalerInvoiceWithBullionAndCashWagePayment() {
        val customer = Customer(
            id = "c-wholesaler-wage",
            name = "بنکدار همکار",
            goldDebtGrams = 0.0,
            cashDebtTomans = 0L
        )

        val craftedItem = BarterCalculationUseCases.calculateCraftedItem(
            title = "النگو",
            karat = Karat.K18,
            grossWeight = 40.0,
            stoneWeight = 0.0,
            spotPrice18k = 25_000_000L,
            wageType = WageType.PERCENTAGE,
            wageInput = 10.0,
            profitPercent = 7.0,
            taxPercent = 9.0
        )

        val invoice = BarterInvoice(
            id = "inv-wholesale-wage",
            invoiceNumber = "1403-401",
            customer = customer,
            customerRole = CustomerRole.WHOLESALER,
            salesItems = listOf(craftedItem), // 40.0g
            payments = listOf(
                SettlementPaymentItem(
                    method = SettlementMethod.BULLION,
                    goldWeight18k = 25.0,
                    bullionAngNumber = "ANG-77"
                ),
                SettlementPaymentItem(
                    method = SettlementMethod.POS,
                    amountTomans = 15_000_000L,
                    trackingCode = "WAGE-POS-1"
                )
            ),
            syncWithLedger = true
        )

        val result = InvoiceLedgerSyncUseCase.generateLedgerSync(invoice, customer)

        assertEquals(3, result.transactionsToCreate.size)
        // 1. 40g gold invoice debt
        assertEquals(LedgerDirection.PAY, result.transactionsToCreate[0].direction)
        assertEquals(40.0, result.transactionsToCreate[0].equivalent750WeightGrams, 0.001)

        // 2. 25g bullion receipt
        assertEquals(LedgerDirection.RECEIVE, result.transactionsToCreate[1].direction)
        assertEquals(25.0, result.transactionsToCreate[1].equivalent750WeightGrams, 0.001)

        // 3. 15M cash wage receipt
        assertEquals(LedgerDirection.RECEIVE, result.transactionsToCreate[2].direction)
        assertEquals(15_000_000L, result.transactionsToCreate[2].amountTomans)

        // Net gold: 40 - 25 = 15.0g
        assertEquals(15.0, result.updatedCustomer.goldDebtGrams, 0.001)
        // Net cash: 0 - 15M = -15M (customer paid 15M cash)
        assertEquals(-15_000_000L, result.updatedCustomer.cashDebtTomans)
    }

    @Test
    fun testReversalRoundTripRestoresOriginalCustomerBalanceForMultiPaymentInvoice() {
        val initialCustomer = Customer(
            id = "c-rev-1",
            name = "مشتری آزمون لغو",
            goldDebtGrams = 12.5,
            cashDebtTomans = 45_000_000L
        )

        val craftedItem = BarterCalculationUseCases.calculateCraftedItem(
            title = "دستبند",
            karat = Karat.K18,
            grossWeight = 10.0,
            stoneWeight = 0.0,
            spotPrice18k = 25_000_000L,
            wageType = WageType.PERCENTAGE,
            wageInput = 10.0,
            profitPercent = 5.0,
            taxPercent = 9.0
        )

        val invoice = BarterInvoice(
            id = "inv-rev",
            customer = initialCustomer,
            customerRole = CustomerRole.RETAIL,
            salesItems = listOf(craftedItem),
            payments = listOf(
                SettlementPaymentItem(
                    method = SettlementMethod.POS,
                    amountTomans = 150_000_000L
                ),
                SettlementPaymentItem(
                    method = SettlementMethod.TRANSFER,
                    amountTomans = 50_000_000L
                )
            ),
            syncWithLedger = true
        )

        val syncResult = InvoiceLedgerSyncUseCase.generateLedgerSync(invoice, initialCustomer)
        assertTrue(syncResult.transactionsToCreate.size >= 2)
        assertNotEquals(initialCustomer.cashDebtTomans, syncResult.updatedCustomer.cashDebtTomans)

        // Now reverse
        val restoredCustomer = InvoiceLedgerSyncUseCase.reverseLedgerSync(
            syncResult.transactionsToCreate,
            syncResult.updatedCustomer
        )

        assertEquals(initialCustomer.goldDebtGrams, restoredCustomer.goldDebtGrams, 0.0001)
        assertEquals(initialCustomer.cashDebtTomans, restoredCustomer.cashDebtTomans)
    }

    @Test
    fun testSyncWithLedgerDisabledProducesNoTransactions() {
        val customer = Customer(id = "c1", name = "تست", goldDebtGrams = 5.0, cashDebtTomans = 100L)
        val invoice = BarterInvoice(
            id = "inv-off",
            customer = customer,
            syncWithLedger = false
        )

        val result = InvoiceLedgerSyncUseCase.generateLedgerSync(invoice, customer)
        assertTrue(result.transactionsToCreate.isEmpty())
        assertEquals(5.0, result.updatedCustomer.goldDebtGrams, 0.001)
        assertEquals(100L, result.updatedCustomer.cashDebtTomans)
    }

    @Test
    fun testReverseLedgerSyncRestoresCustomerBalance() {
        val original = Customer(id = "c1", name = "تست", goldDebtGrams = 10.0, cashDebtTomans = 50_000_000L)

        val goldTx = LedgerTransaction(
            type = LedgerEntryType.GOLD_WEIGHT,
            direction = LedgerDirection.PAY,
            equivalent750WeightGrams = 8.0,
            customerId = "c1"
        )
        val cashTx = LedgerTransaction(
            type = LedgerEntryType.CASH_RIAL,
            direction = LedgerDirection.PAY,
            amountTomans = 20_000_000L,
            customerId = "c1"
        )

        val modified = original.copy(
            goldDebtGrams = original.goldDebtGrams + 8.0,
            cashDebtTomans = original.cashDebtTomans + 20_000_000L
        )
        assertEquals(18.0, modified.goldDebtGrams, 0.001)
        assertEquals(70_000_000L, modified.cashDebtTomans)

        val restored = InvoiceLedgerSyncUseCase.reverseLedgerSync(listOf(goldTx, cashTx), modified)
        assertEquals(10.0, restored.goldDebtGrams, 0.001)
        assertEquals(50_000_000L, restored.cashDebtTomans)
    }

    @Test
    fun testLedgerTransactionWithInvoiceLinkRoundTrip() {
        val tx = LedgerTransaction(
            id = "tx-auto-1",
            customerId = "c-100",
            documentNumber = "IR-1403-999",
            title = "فاکتور تهاتر طلا",
            dateTime = "۱۴۰۳/۰۶/۲۵ ۱۰:۰۰",
            type = LedgerEntryType.GOLD_WEIGHT,
            direction = LedgerDirection.PAY,
            equivalent750WeightGrams = 14.500,
            invoiceId = "inv-target-1",
            invoiceNumber = "IR-1403-999",
            isAutoGenerated = true
        )

        val json = PersistenceJsonCodecs.encodeLedgerTransactions(listOf(tx))
        val decoded = PersistenceJsonCodecs.decodeLedgerTransactions(json).single()

        assertEquals("tx-auto-1", decoded.id)
        assertEquals("c-100", decoded.customerId)
        assertEquals("inv-target-1", decoded.invoiceId)
        assertEquals("IR-1403-999", decoded.invoiceNumber)
        assertTrue(decoded.isAutoGenerated)
        assertEquals(14.500, decoded.equivalent750WeightGrams, 0.001)
    }

    @Test
    fun testBarterInvoiceSerializationRoundTrip() {
        val invoice = BarterInvoice(
            id = "inv-full-1",
            invoiceNumber = "IR-1404-555",
            createdAt = 1715000000000L,
            customer = Customer(id = "c55", name = "جواد زرگر", phone = "09123334455"),
            customerRole = CustomerRole.WHOLESALER,
            spotPrice18k = 24_500_000L,
            salesItems = listOf(
                CraftedGoldItem(
                    id = "item-1",
                    title = "سرویس طلا",
                    karat = Karat.K18,
                    customKaratValue = 750,
                    grossWeight = 12.0,
                    stoneWeight = 0.0,
                    netWeight = 12.0,
                    spotPrice = 24_500_000L,
                    wageType = WageType.PERCENTAGE,
                    wageInput = 8.0,
                    wageAmount = 23_520_000.0,
                    profitPercent = 7.0,
                    profitAmount = 22_241_440.0,
                    taxPercent = 9.0,
                    taxAmount = 4_118_529.6,
                    rawGoldValue = 294_000_000.0,
                    totalPayable = 343_879_969.6,
                    equivalent18kWeight = 12.0
                )
            ),
            payments = listOf(
                SettlementPaymentItem(
                    id = "pay-1",
                    method = SettlementMethod.POS,
                    amountTomans = 200_000_000L,
                    trackingCode = "POS-7788"
                )
            ),
            syncWithLedger = true,
            note = "تحویل فوری در سرای امید"
        )

        val json = PersistenceJsonCodecs.encodeBarterInvoices(listOf(invoice))
        val decodedList = PersistenceJsonCodecs.decodeBarterInvoices(json)

        assertEquals(1, decodedList.size)
        val decoded = decodedList.single()

        assertEquals("inv-full-1", decoded.id)
        assertEquals("IR-1404-555", decoded.invoiceNumber)
        assertEquals("جواد زرگر", decoded.customer?.name)
        assertEquals(CustomerRole.WHOLESALER, decoded.customerRole)
        assertEquals(24_500_000L, decoded.spotPrice18k)
        assertEquals(1, decoded.salesItems.size)
        assertEquals("سرویس طلا", decoded.salesItems.first().title)
        assertEquals(1, decoded.payments.size)
        assertEquals(200_000_000L, decoded.payments.first().amountTomans)
        assertTrue(decoded.syncWithLedger)
        assertEquals("تحویل فوری در سرای امید", decoded.note)
        assertEquals("1404-555", decoded.cleanInvoiceNumber)
    }

    @Test
    fun testCleanInvoiceNumberAndCleanDocumentNumberRemovesIRPrefix() {
        val legacyInvoice = BarterInvoice(
            invoiceNumber = "IR-1403-888"
        )
        assertEquals("1403-888", legacyInvoice.cleanInvoiceNumber)

        val legacyTx = LedgerTransaction(
            customerId = "c1",
            documentNumber = "IR-8842",
            invoiceNumber = "IR-1403-777"
        )
        assertEquals("8842", legacyTx.cleanDocumentNumber)
        assertEquals("1403-777", legacyTx.cleanInvoiceNumber)

        val modernInvoice = BarterInvoice(
            invoiceNumber = "1403-999"
        )
        assertEquals("1403-999", modernInvoice.cleanInvoiceNumber)
    }
}
