package com.goldex.companion.data.local.db.entities

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

@Entity(
    tableName = "ledger_transactions",
    indices = [
        Index(value = ["customerId"]),
        Index(value = ["invoiceId"])
    ]
)
data class LedgerTransactionEntity(
    @PrimaryKey
    val id: String,
    val customerId: String,
    val documentNumber: String = "",
    val title: String = "",
    val dateTime: String = "",
    val type: String = "GOLD_WEIGHT",
    val direction: String = "RECEIVE",
    val goldCategory: String = "آبشده",
    val scaleWeightGrams: Double = 0.0,
    val karat: Int = 750,
    val equivalent750WeightGrams: Double = 0.0,
    val angNumber: String = "",
    val labName: String = "",
    val amountTomans: Long = 0L,
    val paymentMethod: String = "حواله بانکی / پایا",
    val destinationBank: String = "",
    val trackingCode: String = "",
    val note: String = "",
    val tagBadge: String = "",
    val resultingGoldBalance: Double = 0.0,
    val resultingCashBalance: Long = 0L,
    val timestamp: Long = System.currentTimeMillis(),
    val invoiceId: String? = null,
    val invoiceNumber: String? = null,
    val isAutoGenerated: Boolean = false
)
