package com.goldex.companion.data.local.db.mappers

import com.goldex.companion.data.local.db.entities.LedgerTransactionEntity
import com.goldex.companion.model.LedgerDirection
import com.goldex.companion.model.LedgerEntryType
import com.goldex.companion.model.LedgerTransaction
import com.goldex.companion.data.PersistenceJsonCodecs

fun LedgerTransactionEntity.toDomain(): LedgerTransaction {
    val entryType = try {
        LedgerEntryType.valueOf(type)
    } catch (_: Exception) {
        LedgerEntryType.GOLD_WEIGHT
    }

    val dir = try {
        LedgerDirection.valueOf(direction)
    } catch (_: Exception) {
        LedgerDirection.RECEIVE
    }

    return LedgerTransaction(
        id = id,
        customerId = customerId,
        documentNumber = documentNumber,
        title = title,
        dateTime = dateTime,
        type = entryType,
        direction = dir,
        goldCategory = goldCategory,
        scaleWeightGrams = scaleWeightGrams,
        karat = karat,
        equivalent750WeightGrams = equivalent750WeightGrams,
        angNumber = angNumber,
        labName = labName,
        amountTomans = amountTomans,
        paymentMethod = paymentMethod,
        destinationBank = destinationBank,
        trackingCode = trackingCode,
        note = note,
        tagBadge = tagBadge,
        resultingGoldBalance = resultingGoldBalance,
        resultingCashBalance = resultingCashBalance,
        timestamp = timestamp,
        invoiceId = invoiceId,
        invoiceNumber = invoiceNumber,
        isAutoGenerated = isAutoGenerated,
        settlement = PersistenceJsonCodecs.decodeLedgerSettlement(settlementJson)
    )
}

fun LedgerTransaction.toEntity(): LedgerTransactionEntity {
    return LedgerTransactionEntity(
        id = id,
        customerId = customerId,
        documentNumber = documentNumber,
        title = title,
        dateTime = dateTime,
        type = type.name,
        direction = direction.name,
        goldCategory = goldCategory,
        scaleWeightGrams = scaleWeightGrams,
        karat = karat,
        equivalent750WeightGrams = equivalent750WeightGrams,
        angNumber = angNumber,
        labName = labName,
        amountTomans = amountTomans,
        paymentMethod = paymentMethod,
        destinationBank = destinationBank,
        trackingCode = trackingCode,
        note = note,
        tagBadge = tagBadge,
        resultingGoldBalance = resultingGoldBalance,
        resultingCashBalance = resultingCashBalance,
        timestamp = timestamp,
        invoiceId = invoiceId,
        invoiceNumber = invoiceNumber,
        isAutoGenerated = isAutoGenerated,
        settlementJson = settlement?.let(PersistenceJsonCodecs::encodeLedgerSettlement) ?: ""
    )
}
